require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '10.0'
target 'WatchApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'

  target 'WatchAppTests' do
    inherit! :complete
    # Pods for testingpod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'WatchApp-tvOS' do
  # Pods for WatchApp-tvOS

  target 'WatchApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
